"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

import cStringIO as StringIO
import struct

class asv_to_auv_gps_owtt_t(object):
    __slots__ = ["utime", "lat", "lon", "hdop", "owtt"]

    def __init__(self):
        self.utime = 0
        self.lat = 0.0
        self.lon = 0.0
        self.hdop = 0.0
        self.owtt = 0.0

    def encode(self):
        buf = StringIO.StringIO()
        buf.write(asv_to_auv_gps_owtt_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qdddd", self.utime, self.lat, self.lon, self.hdop, self.owtt))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = StringIO.StringIO(data)
        if buf.read(8) != asv_to_auv_gps_owtt_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return asv_to_auv_gps_owtt_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = asv_to_auv_gps_owtt_t()
        self.utime, self.lat, self.lon, self.hdop, self.owtt = struct.unpack(">qdddd", buf.read(40))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if asv_to_auv_gps_owtt_t in parents: return 0
        tmphash = (0x29ce3a66864e2e90) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if asv_to_auv_gps_owtt_t._packed_fingerprint is None:
            asv_to_auv_gps_owtt_t._packed_fingerprint = struct.pack(">Q", asv_to_auv_gps_owtt_t._get_hash_recursive([]))
        return asv_to_auv_gps_owtt_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

