/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package acomms;
 
import java.io.*;
import java.nio.*;
import java.util.*;
import lcm.lcm.*;
 
public final class asv_to_auv_gps_owtt_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public double lat;
    public double lon;
    public double hdop;
    public double owtt;
 
    public asv_to_auv_gps_owtt_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x29ce3a66864e2e90L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class>());
    }
 
    public static long _hashRecursive(ArrayList<Class> classes)
    {
        if (classes.contains(acomms.asv_to_auv_gps_owtt_t.class))
            return 0L;
 
        classes.add(acomms.asv_to_auv_gps_owtt_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.utime); 
 
        outs.writeDouble(this.lat); 
 
        outs.writeDouble(this.lon); 
 
        outs.writeDouble(this.hdop); 
 
        outs.writeDouble(this.owtt); 
 
    }
 
    public asv_to_auv_gps_owtt_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public asv_to_auv_gps_owtt_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static acomms.asv_to_auv_gps_owtt_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        acomms.asv_to_auv_gps_owtt_t o = new acomms.asv_to_auv_gps_owtt_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.utime = ins.readLong();
 
        this.lat = ins.readDouble();
 
        this.lon = ins.readDouble();
 
        this.hdop = ins.readDouble();
 
        this.owtt = ins.readDouble();
 
    }
 
    public acomms.asv_to_auv_gps_owtt_t copy()
    {
        acomms.asv_to_auv_gps_owtt_t outobj = new acomms.asv_to_auv_gps_owtt_t();
        outobj.utime = this.utime;
 
        outobj.lat = this.lat;
 
        outobj.lon = this.lon;
 
        outobj.hdop = this.hdop;
 
        outobj.owtt = this.owtt;
 
        return outobj;
    }
 
}

