"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

import cStringIO as StringIO
import struct

class auv_to_asv_state_t(object):
    __slots__ = ["utime", "lat", "lon", "depth", "nextwp"]

    def __init__(self):
        self.utime = 0
        self.lat = 0.0
        self.lon = 0.0
        self.depth = 0.0
        self.nextwp = 0

    def encode(self):
        buf = StringIO.StringIO()
        buf.write(auv_to_asv_state_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qdddh", self.utime, self.lat, self.lon, self.depth, self.nextwp))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = StringIO.StringIO(data)
        if buf.read(8) != auv_to_asv_state_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return auv_to_asv_state_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = auv_to_asv_state_t()
        self.utime, self.lat, self.lon, self.depth, self.nextwp = struct.unpack(">qdddh", buf.read(34))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if auv_to_asv_state_t in parents: return 0
        tmphash = (0xd35427638dc230d1) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if auv_to_asv_state_t._packed_fingerprint is None:
            auv_to_asv_state_t._packed_fingerprint = struct.pack(">Q", auv_to_asv_state_t._get_hash_recursive([]))
        return auv_to_asv_state_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

