"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

import cStringIO as StringIO
import struct

class cmd_ping_t(object):
    __slots__ = ["utime", "ping_source", "ping_destination"]

    def __init__(self):
        self.utime = 0
        self.ping_source = 0
        self.ping_destination = 0

    def encode(self):
        buf = StringIO.StringIO()
        buf.write(cmd_ping_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qhh", self.utime, self.ping_source, self.ping_destination))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = StringIO.StringIO(data)
        if buf.read(8) != cmd_ping_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return cmd_ping_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = cmd_ping_t()
        self.utime, self.ping_source, self.ping_destination = struct.unpack(">qhh", buf.read(12))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if cmd_ping_t in parents: return 0
        tmphash = (0x50f76824a46757e3) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if cmd_ping_t._packed_fingerprint is None:
            cmd_ping_t._packed_fingerprint = struct.pack(">Q", cmd_ping_t._get_hash_recursive([]))
        return cmd_ping_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

