/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package acomms;
 
import java.io.*;
import java.nio.*;
import java.util.*;
import lcm.lcm.*;
 
public final class owtt_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public double owtt;
 
    public owtt_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xff4cbfe5d928caf9L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class>());
    }
 
    public static long _hashRecursive(ArrayList<Class> classes)
    {
        if (classes.contains(acomms.owtt_t.class))
            return 0L;
 
        classes.add(acomms.owtt_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.utime); 
 
        outs.writeDouble(this.owtt); 
 
    }
 
    public owtt_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public owtt_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static acomms.owtt_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        acomms.owtt_t o = new acomms.owtt_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.utime = ins.readLong();
 
        this.owtt = ins.readDouble();
 
    }
 
    public acomms.owtt_t copy()
    {
        acomms.owtt_t outobj = new acomms.owtt_t();
        outobj.utime = this.utime;
 
        outobj.owtt = this.owtt;
 
        return outobj;
    }
 
}

