"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

import cStringIO as StringIO
import struct

class owtt_t(object):
    __slots__ = ["utime", "owtt"]

    def __init__(self):
        self.utime = 0
        self.owtt = 0.0

    def encode(self):
        buf = StringIO.StringIO()
        buf.write(owtt_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qd", self.utime, self.owtt))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = StringIO.StringIO(data)
        if buf.read(8) != owtt_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return owtt_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = owtt_t()
        self.utime, self.owtt = struct.unpack(">qd", buf.read(16))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if owtt_t in parents: return 0
        tmphash = (0xff4cbfe5d928caf9) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if owtt_t._packed_fingerprint is None:
            owtt_t._packed_fingerprint = struct.pack(">Q", owtt_t._get_hash_recursive([]))
        return owtt_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

